// src/components/Gallery.svelte
<script>
  export let images = [];
  export let name = "";

  let modalOpen = false;
  let modalIndex = 0;

  function openImage(index) {
    modalOpen = true;
    modalIndex = index;
  }

  function closeModal() {
    modalOpen = false;
  }

  function moveRight() {
    modalIndex += 1;
    if (modalIndex > images.length - 1) modalIndex = 0;
  }

  function moveLeft() {
    modalIndex -= 1;
    if (modalIndex < 0) modalIndex = images.length - 1;
  }
</script>

<div id="gallery" class="flex flex-col gap-4">
  {#each images as image, i}
    <button on:click={() => openImage(i)}>
      <img class="" src={image} alt={name} />
    </button>
  {/each}
</div>

{#if modalOpen}
  <button
    id="lightbox"
    class="fixed top-0 right-0 left-0 bottom-0 z-50 bg-gray-600/90 flex items-center justify-center"
    on:click|stopPropagation={closeModal}
    on:keypress={(e) => {
      if (e.key == "Enter") {
        closeModal();
      }
    }}
  >
    <img
      class="object-contain h-full w-auto"
      src={images[modalIndex]}
      alt={name}
      on:click|stopPropagation|preventDefault
      on:keypress|stopPropagation|preventDefault
    />

    <button
      id="move-right"
      class="fixed right-0 sm:bg-slate-50/30 text-slate-50 h-full sm:h-1/3 sm:w-16 w-32"
      on:click|stopPropagation={moveRight}
    >
      <i class="fa-solid fa-chevron-right text-lg hidden sm:block" />
    </button>

    <button
      id="move-left"
      class="fixed left-0 sm:bg-slate-50/30 text-slate-50 h-full sm:h-1/3 sm:w-16 w-32"
      on:click|stopPropagation={moveLeft}
    >
      <i class="fa-solid fa-chevron-left text-lg hidden sm:block" />
    </button>

    <button
      id="close-modal"
      on:click|stopPropagation={closeModal}
      class="fixed top-0 right-0 "
    >
      <i class="fa-solid fa-x m-4 text-slate-50 text-lg" />
    </button>
  </button>
{/if}

<svelte:window
  on:keydown={(e) => {
    switch (e.key) {
      case "Escape":
        closeModal();
        break;

      case "ArrowRight":
        moveRight();
        break;

      case "ArrowLeft":
        moveLeft();
        break;
        
      default:
        console.log(e.key);
    }
  }}
/>

// src/components/Gallery.tsx
import { MouseEvent, useEffect, useState } from "react";
import { Button } from "./ui/button";

export type Props = {
  images: [];
  name: string;
};

export default function Gallery(props: Props) {
  const { images, name } = props;

  const windowKey = (e: KeyboardEvent) => {
    switch (e.key) {
      case "Escape":
        closeModal();
        break;

      case "ArrowRight":
        moveRight();
        break;

      case "ArrowLeft":
        moveLeft();
        break;

      default:
        console.log(e.key);
    }
  };

  const [modalOpen, setModalOpen] = useState(false);
  const [modalIndex, setModalIndex] = useState(0);

  function stopPrevent(event: any) {
    event.preventDefault();
    event.stopPropagation();
  }

  function openImage(index: number) {
    setModalOpen(true);
    setModalIndex(index);
  }

  function closeModal() {
    setModalOpen(false);
  }

  function moveRight() {
    setModalIndex((prev) => (prev = prev === images.length - 1 ? 0 : prev + 1));
  }

  function moveLeft() {
    setModalIndex((prev) => (prev = prev === 0 ? images.length - 1 : prev - 1));
  }

  return (
    <>
      <div id="gallery" className="flex flex-col gap-4">
        {images.map((image, i) => (
          <button key={i} onClick={() => openImage(i)}>
            <img className="" src={image} alt={name} />
          </button>
        ))}
      </div>

      {modalOpen && (
        <div
          className="fixed top-0 right-0 left-0 bottom-0 z-50 bg-gray-600/90 flex items-center justify-center"
          onClick={(e) => {
            closeModal();
          }}
        >
          <img
            className="object-contain h-full w-auto"
            src={images[modalIndex]}
            alt={name}
            onClick={stopPrevent}
            onKeyDown={stopPrevent}
          />

          <button
            className="fixed right-0 sm:bg-slate-50/30 text-slate-50 h-full sm:h-1/3 sm:w-16 w-32"
            onClick={(e) => {
              moveRight();
              stopPrevent(e);
            }}
          >
            <i className="fa-solid fa-chevron-right text-lg hidden sm:block" />
          </button>

          <button
            className="fixed left-0 sm:bg-slate-50/30 text-slate-50 h-full sm:h-1/3 sm:w-16 w-32"
            onClick={(e) => {
              e.stopPropagation();
              moveLeft();
            }}
          >
            <i className="fa-solid fa-chevron-left text-lg hidden sm:block" />
          </button>

          <Button
            onClick={(e) => {
              stopPrevent(e);
              closeModal();
            }}
            variant="ghost"
            size="icon"
            className="fixed top-0 right-0 mt-4 mr-4"
          >
            <i className="fa-solid fa-x text-lg" />
          </Button>
        </div>
      )}
    </>
  );
}
