// src/components/Navbar.svelte
<script>
  import contacts from "../data/contact.json";
  // import { getAlbums } from "../utils/getAlbums";

  // const albums = await getAlbums()
  let isOpen = false;
</script>

<nav
  class="w-full bg-gray-50 shadow-lg top-0 z-50 px-4 md:px-8 sticky md:flex md:justify-between md:items-center"
>
  <div class="flex items-center z-40 justify-between">
    <a id="logo" href="/" class="flex items-center gap-2 py-4">
      <img class="h-12" src="/favicon.png" alt="logo" />
      Riley Paul
    </a>
    <button
      id="nav-toggle-button"
      class="h-12 focus:outline-none flex items-center justify-center md:hidden"
      on:click={() => (isOpen = !isOpen)}
    >
      <i class="fa-solid text-lg px-4 {isOpen ? 'fa-x' : 'fa-bars'}" />
    </button>
  </div>

  <ul
    id="header-links"
    class="flex-col gap-4 py-4 md:flex md:flex-row items-center text-gray-600 {isOpen
      ? 'flex'
      : 'hidden'}"
  >
    <li class="link-container"><a href="/">Portfolio</a></li>
    <li class="link-container"><a href="/blog/">Blog</a></li>
    <li class="link-container"><a href="/about/">About</a></li>
    <div id="social" class="flex gap-4">
      {#each contacts as c (c.name)}
        <li class="link-container">
          <a href={c.link} target="_blank" rel="noopener noreferrer">
            <i class={c.icon} />
          </a>
        </li>
      {/each}
    </div>
  </ul>

  <!-- <span id="page-title">{title}</span> -->
</nav>

<svelte:window
  on:keydown={(e) => {
    if (e.key == "Escape") {
      isOpen = false;
    }
  }}
/>

// src/components/Navbar.tsx
import { useEffect, useState } from "react";
import { Button } from "./ui/button";
import { getCollection } from "astro:content";

const contacts = await getCollection("contact")

export default function Navbar() {
  const [isOpen, setIsOpen] = useState(false);

  const collapse = (event: KeyboardEvent) => {
    if (event.key === "Escape") setIsOpen(false);
  };

  useEffect(() => {
    window.addEventListener("keydown", collapse);
    return () => window.removeEventListener("keydown", collapse);
  }, []);

  return (
    <nav className="w-full bg-gray-50 shadow-lg top-0 z-50 px-4 md:px-8 sticky md:flex md:justify-between md:items-center">
      <div className="flex items-center z-40 justify-between">
        <a id="logo" href="/" className="flex items-center gap-2 py-4">
          <img className="h-12" src="/favicon.png" alt="logo" />
          Riley Paul
        </a>
        <Button
          variant="ghost"
          className="md:hidden"
          size="icon"
          onClick={() => setIsOpen((prev) => !prev)}
        >
          <i
            className={`fa-solid text-lg px-4 ${isOpen ? "fa-x" : "fa-bars"}`}
          />
        </Button>
      </div>

      <ul
        id="header-links"
        className={`flex-col py-4 md:flex md:flex-row items-center text-gray-600 ${
          isOpen ? "flex" : "hidden"
        }`}
      >
        <li>
          <a href="/">
            <Button variant="link" size="lg" className="px-4">
              Portfolio
            </Button>
          </a>
        </li>
        <li>
          <a href="/blog/">
            <Button variant="link" size="lg" className="px-4">
              Blog
            </Button>
          </a>
        </li>
        <li>
          <a href="/about/">
            <Button variant="link" size="lg" className="px-4">
              About
            </Button>
          </a>
        </li>
        <div id="social" className="flex gap-2">
          {contacts.map((c) => (
            <li key={c.data.link}>
              <a href={c.data.link} target="_blank" rel="noopener noreferrer">
                <Button variant="link" size="icon" className="px-4">
                  <i className={`${c.data.icon}`} />
                </Button>
              </a>
            </li>
          ))}
        </div>
      </ul>

      {/* <span id="page-title">{title}</span> */}
    </nav>
  );
}
